// ===================================================
// 🔹 Статические Custom IDs
// ===================================================

export const CUSTOM_IDS = {
	OPEN_APPLICATION: "open_application",
	OPEN_FAMILY_APPLICATION: "OPEN_FAMILY_APPLICATION",
	MODAL_NEW: "application_modal_",
	FAMILY_MODAL_NEW: "family_application_modal_",
	MODAL_EDIT: "application_modal_edit_",
	DECLINE_REASON: "decline_reason_",
	REASON: "reason",
	ACCEPT: "accept_",
	ACCEPT_HIVE: "ACCEPT_HIVE_",
	DECLINE_HIVE: "DECLINE_HIVE_",
	DECLINE: "decline_",
	CHANGE: "change_",
	COPY_TEXT: "copy_text",
	GAME_NAME: "game_name",
	HIVE_TYPE: "type",
	STORY: "story",
	VIDEO: "video",
	TARGET: "target",
	APPLICATION_FAMILY_NAME: "Игровой никнейм | Статик",
	APPLICATION_FAMILY_AGE: "Ваш возраст ООС",
	APPLICATION_FAMILY_TARGET: "Цель вступления",
	APPLICATION_FAMILY_HOW_TO_KNOW: "Как узнали о семье",
	APPLICATION_FAMILY_LINK: "Скрин персонажей",
	FAMILY_ACCEPT_APPLICATION_IN_FAMILY: "FAMILY_ACCEPT_APPLICATION_IN_FAMILY_",
	FAMILY_DECLINE_APPLICATION_IN_FAMILY: "FAMILY_DECLINE_APPLICATION_IN_FAMILY_",
	FAMILY_CALL_APPLICATION_IN_FAMILY: "FAMILY_CALL_APPLICATION_IN_FAMILY_",
	FAMILY_DECLINE_REASON_IN_FAMILY: "FAMILY_DECLINE_REASON_IN_FAMILY_",
	FAMILY_REASON_IN_FAMILY: "FAMILY_REASON_IN_FAMILY_",
	MARKET_BUTTON: "market_buy_",
};

export const CUSTOM_COMMAND = {
	DB_APPLICATION: "заявка_улики",
	FAMILY_APPLICATION: "заявк_в_семью",
	RECRUIT_STATS: "recruit-stats",
	STAFF_LIST: "staff-list",
	BALANCE: "balance",
	VOICETOP: "voice-top",
	STREAMER_ADD: "streamer-add",
	STREAMER_REMOVE: "streamer-remove",
	BALANCE_GIVE: "balance-give",
	BALANCE_TAKE: "balance-take",
	BALANCE_CHECK: "balance-check",
	MARKET: "market",
	MARKET_ADD: "market-add",
	MUTE: "mute",
	BAN: "ban",
	WARN: "warn",
	UNWARN: "unwarn",
	UNBAN: "unban",
	UNMUTE: "unmute",

}
