// ===================================================
// 🔹 Статические Custom IDs
// ===================================================

export const CUSTOM_IDS = {
	OPEN_APPLICATION: "open_application",
	OPEN_FAMILY_APPLICATION: "OPEN_FAMILY_APPLICATION",
	MODAL_NEW: "application_modal_",
	FAMILY_MODAL_NEW: "family_application_modal_",
	HIVE_ORGTYPE_SELECT: "hive_orgtype_select",
	HIVE_ORG_SELECT: "hive_org_select",
	HIVE_ACCEPT: "hive_accept",
	HIVE_DECLINE: "hive_decline",
	HIVE_DECLINE_REASON: "hive_decline_reason",
	HIVE_TYPE: "type",
	TARGET: "target",
	APPLICATION_FAMILY_NAME: "Игровой никнейм | Статик",
	APPLICATION_FAMILY_AGE: "Ваш возраст ООС",
	APPLICATION_FAMILY_TARGET: "Цель вступления",
	APPLICATION_FAMILY_HOW_TO_KNOW: "Как узнали о семье",
	APPLICATION_FAMILY_LINK: "Скрин персонажей",
	FAMILY_ACCEPT_APPLICATION_IN_FAMILY: "FAMILY_ACCEPT_APPLICATION_IN_FAMILY_",
	FAMILY_DECLINE_APPLICATION_IN_FAMILY: "FAMILY_DECLINE_APPLICATION_IN_FAMILY_",
	FAMILY_CALL_APPLICATION_IN_FAMILY: "FAMILY_CALL_APPLICATION_IN_FAMILY_",
	FAMILY_DECLINE_REASON_IN_FAMILY: "FAMILY_DECLINE_REASON_IN_FAMILY_",
	FAMILY_REASON_IN_FAMILY: "FAMILY_REASON_IN_FAMILY_",
	MARKET_BUTTON: "market_buy_",
	ROLE_BUY: "role_buy_",
	MARKET_TOGGLE_STATE: "market_toggle_state",
	MARKET_MANAGE_ADD: "market_manage_add",
	MARKET_MANAGE_EDIT_ITEM: "market_manage_edit_item:",
	MARKET_MODAL_ADD: "market_modal_add",
	MARKET_MODAL_EDIT_ITEM: "market_modal_edit_item:",
	MARKET_MODAL_NAME: "market_modal_name",
	MARKET_MODAL_PRICE: "market_modal_price",
	MARKET_ORDER_TAKE: "market_order_take:",
	MARKET_ORDER_COMPLETE: "market_order_complete:",
	MARKET_ORDER_DECLINE: "market_order_decline:",


	HIVE_SELECT_FAMILY: "hive_select_family",
	HIVE_SELECT_FRACTION: "hive_select_fraction",
	HIVE_SELECT_HIVETYPE: "hive_select_hivetype",
	SET_FORM: "hive_set_form:",
	// модалки
	HIVE_MODAL_NEW: "hive_modal_new",
	MODAL_EDIT: "modal_edit_",
	DECLINE_REASON: "decline_reason_",

	// кнопки в личном канале заявки
	ACCEPT: "accept_",
	DECLINE: "decline_",
	CHANGE: "change_",

	// лог: копирование и финализация
	COPY_TEXT: "copy_text_",
	ACCEPT_HIVE: "accept_hive_",
	DECLINE_HIVE: "decline_hive_",
	CREATE_CASE: "hive_create_case:",
	// inputs
	GAME_NAME: "game_name",
	STORY: "story",
	VIDEO: "video",
	REASON: "reason",

	WEEKLY_FEE_PRICE_EDIT: "weekly_fee_price_edit",
	WEEKLY_FEE_PRICE_MODAL: "weekly_fee_price_modal",
	WEEKLY_FEE_PRICE_INPUT: "weekly_fee_price_input",
	FAMILY_AFK_ENTER: "family_afk_enter",
	FAMILY_AFK_LIST: "family_afk_list",
	FAMILY_AFK_EXIT: "family_afk_exit",
	FAMILY_AFK_MODAL: "family_afk_modal",
	FAMILY_AFK_HOURS_INPUT: "family_afk_hours_input",
	FAMILY_AFK_REASON_INPUT: "family_afk_reason_input",
	FAMILY_VACATION_ENTER: "family_vacation_enter",
	FAMILY_VACATION_LIST: "family_vacation_list",
	FAMILY_VACATION_EXIT: "family_vacation_exit",
	FAMILY_VACATION_MODAL: "family_vacation_modal",
	FAMILY_VACATION_UNTIL_INPUT: "family_vacation_until_input",
	FAMILY_VACATION_REASON_INPUT: "family_vacation_reason_input",
	FAMILY_PROMO_REQUEST: "family_promo_request",
	FAMILY_PROMO_COMPLETE: "family_promo_complete:",
	FAMILY_PROMO_DECLINE: "family_promo_decline:",
	FAMILY_PROMO_DECLINE_MODAL: "family_promo_decline_modal:",
	FAMILY_PROMO_DECLINE_REASON_INPUT: "family_promo_decline_reason_input",
	FAMILY_IMPROVEMENT_REQUEST_SELECT: "family_improvement_request_select",
	FAMILY_IMPROVEMENT_REQUEST_MODAL: "family_improvement_request_modal:",
	FAMILY_IMPROVEMENT_NICKNAME_INPUT: "family_improvement_nickname_input",
	FAMILY_IMPROVEMENT_REASON_INPUT: "family_improvement_reason_input",
	FAMILY_IMPROVEMENT_ACCEPT: "family_improvement_accept:",
	FAMILY_IMPROVEMENT_DECLINE: "family_improvement_decline:",
	FAMILY_IMPROVEMENT_DECLINE_MODAL: "family_improvement_decline_modal:",
	FAMILY_IMPROVEMENT_DECLINE_REASON_INPUT: "family_improvement_decline_reason_input",
	FAMILY_GAMES_ROLE_TOGGLE: "family_games_role_toggle:",
	FAMILY_GAMES_PANEL_CREATE: "family_games_panel_create",
	FAMILY_GAMES_PANEL_EDIT: "family_games_panel_edit:",
	FAMILY_GAMES_PANEL_DELETE: "family_games_panel_delete:",
	FAMILY_GAMES_MODAL_CREATE: "family_games_modal_create",
	FAMILY_GAMES_MODAL_EDIT: "family_games_modal_edit:",
	FAMILY_GAMES_MODAL_NAME: "family_games_modal_name",
	COINFLIP_JOIN: "coinflip_join:",
	COINFLIP_DECLINE: "coinflip_decline:",
	DICE_JOIN: "dice_join:",
	DICE_DECLINE: "dice_decline:",
	GIVEAWAY_JOIN: "giveaway_join:",
	GIVEAWAY_PANEL_CREATE: "giveaway_panel_create",
	GIVEAWAY_PANEL_REROLL: "giveaway_panel_reroll",
	GIVEAWAY_PANEL_REROLL_SELECT: "giveaway_panel_reroll_select",
	GIVEAWAY_MODAL_CREATE: "giveaway_modal_create",
	GIVEAWAY_MODAL_PRIZE: "giveaway_modal_prize",
	GIVEAWAY_MODAL_IMAGE_URL: "giveaway_modal_image_url",
	GIVEAWAY_MODAL_CONDITIONS: "giveaway_modal_conditions",
	GIVEAWAY_MODAL_WINNERS: "giveaway_modal_winners",
	GIVEAWAY_MODAL_END_TIME: "giveaway_modal_end_time",
};

export const CUSTOM_COMMAND = {
	DB_APPLICATION: "заявка_улики",
	DB_ORGANISATION_ADD: "organisation-add",
	DB_HIVE_PAYOUT: "pay-hive",
	DB_INTERNSHIP: "internship",
	DB_ORGANISATIONS_LIST: "organisation-list",
	FAMILY_APPLICATION: "заявк_в_семью",
	RECRUIT_STATS: "recruit-stats",
	RECRUIT_PERFORMANCE: "recruit-performance",
	RECRUIT: "recruit",
	STAFF_LIST: "staff-list",
	BALANCE: "balance",
	PROFILE: "profile",
	VOICETOP: "voice-top",
	STREAMER_ADD: "streamer-add",
	STREAMER_REMOVE: "streamer-remove",
	BALANCE_GIVE: "balance-give",
	BALANCE_TAKE: "balance-take",
	BALANCE_CHECK: "balance-check",
	MARKET: "market",
	MARKET_ADD: "market-add",
	MARKET_REMOVE: "market-remove",
	MUTE: "mute",
	BAN: "ban",
	WARN: "warn",
	UNWARN: "unwarn",
	UNBAN: "unban",
	UNMUTE: "unmute",
	DB_HIVE_STATS: "hive-stats",
	FEE_ADD: "fee-add",
	FEE_REMOVE: "fee-remove",
	FEE_PANEL: "fee-panel",
	FAMILY_PANEL: "family-panel-reset",
	FAMILY_NAVIGATION: "navigation-panel",
	GIVEAWAY: "giveaway",
	COINFLIP: "coinflip",
	DICE: "dice",
	GAMES: "games",
	RANK: "rank",
}
