import {config} from "./env";

export const CHANNEL_IDS = {
	LOG: config.DB_LOG_CHANNEL_ID,
	LOG_HIGH: config.DB_LOG_HIGH_CHANNEL_ID,
	FAMILY_LOG: config.FAMILY_LOG_CHANNEL_ID,
	FAMILY_IMPROVEMENT_INFO: config.FAMILY_IMPROVMENT_SYSTEM_CHANNEL_ID,
	FAMILY_IMPROVEMENT_REQUESTS: config.FAMILY_REQUEST_IMPROVMENT_SYSTEM_CHANNEL_ID,
	FAMILY_IMPROVEMENT_APPLICATIONS:
		config.FAMILY_REQUEST_IMPROVMENT_SYSTEM_APPLICATION_CHANNEL_ID,
	FAMILY_LEADERBOARD: config.FAMILY_LEADERBOARD_CHANNEL_ID,
	FAMILY_MARKET_LOG: config.FAMILY_MARKET_LOG_CHANNEL_ID,
	FAMILY_WELCOME: config.FAMILY_WELCOME_CHANNEL_ID,
	FAMILY_AFK_MEMBERS: config.FAMILY_AFK_FOR_MEMBERS_CHANNEL_ID,
	FAMILY_EVENTS: config.FAMILY_EVENTS_CHANNEL_ID,
	APPLICATION_CATEGORY: config.DB_CATEGORY_ID,
	EVENTS_NOTIFY: config.EVENTS_NOTIFY_CHANNEL_ID
};
