import * as dotenv from "dotenv";
import 'dotenv/config';
dotenv.config();

export const config = {
	TOKEN: process.env.TOKEN!,
	DB_CATEGORY_ID: process.env.DB_CATEGORY_ID!,
	DB_LOG_CHANNEL_ID: process.env.DB_LOG_CHANNEL_ID!,
	FAMILY_SERVER_GUID: process.env.FAMILY_SERVER_GUID!,
	FAMILY_RECRUIT_CHANNEL_ID: process.env.FAMILY_RECRUIT_CHANNEL_ID!,
	FAMILY_RECRUIT_CATEGORY_ID: process.env.FAMILY_RECRUIT_CATEGORY_ID!,
	FAMILY_RECRUIT_LOG_ID: process.env.FAMILY_RECRUIT_LOG_ID!,
	FAMILY_RECRUIT_STATS_CHANNEL_ID: process.env.FAMILY_RECRUIT_STATS_CHANNEL_ID!,
	FAMILY_RECRUIT_ROLE_IDS: process.env.FAMILY_RECRUIT_ROLE_IDS!,
	FAMILY_LOG_CHANNEL_ID: process.env.FAMILY_LOG_CHANNEL_ID!,
};